server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://35.231.51.249:5432/DataStream
    username: postgres
    password: SecurePostgresPass123!
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

nifi:
  base-url: https://localhost:8443/nifi-api
  username: f9a80316-5103-4618-b90e-a37c886cb5d9
  password: Hh3G6vrgePoxLM+maTdMnKmobHB2AU30
  root-group-id: 971161e6-019d-1000-a3cf-b33595a62fdd

flow:
  scheduling:
    query: 5 sec

  dbcp:
    driverClass: com.mysql.cj.jdbc.Driver
    driverLocation: C:/mysql/mysql-connector-j-9.6.0.jar