server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nifi_dynamic_flow
    username: postgres
    password: FIS@123.
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

nifi:
  base-url: https://localhost:8443/nifi-api
  username: e972ec5f-90bd-4e90-810d-c2a47fd67f08
  password: Xelx6tAH6uJHDLk409u3vekQsK/4bD42
  root-group-id: 9b1dea98-019d-1000-85f8-693f197078e6

flow:
  scheduling:
    query: 5 sec

  dbcp:
    driverClass: com.mysql.cj.jdbc.Driver
    driverLocation: C:/nifi/nifi-1.28.1/lib/mysql-connector-j-8.2.0.jar